### ISSUE TITLE
Dokuwiki Datatable plugin broken since last update 

### ISSUE THREAD

**Issue by paulhuysing** [LotarProject/dokuwiki-plugin-datatables#12]
Updated datatable plugin on 27/10/15 with latest update.
Datatable plugin not working now (Release 2014-05-05a "Ponder Stibbons")

Plugin is now not rendering the table as per design spec.  No search, sort or other functionality i.e. it just looks like a normal table.

Not sure what other information to provide

**Comment by mrkslrnz** [comment]
I can confirm that. As far as I can tell, the JavaScript library for DataTables is not loaded and neither is jQuery. I can't find it anywhere in the generated HTML of the wiki although the plugin is installed and activated.

Have a look here: http://wiki.lrnz.name/doku.php/playground:playground

**Comment by LotarProject** [comment]
Hi! I have tested the @mrkslrnz 's code and work, "only" if the page is created outside the "playground" because this namespace is present in the ``excludedPages`` setting (default value ``(wiki|playground)``).

Create a test page outside the playground or change the value of ``excludedPages``.

At your disposal.

Best regards,
Joseph

**Comment by paulhuysing** [comment]
The plugin works on your http://lotar.altervista.org/dokuwiki/wiki/plugin/datatables site, so perhaps it only relates to backward compatability with Ponder Stibbons since the latest plugin update?

**Comment by mrkslrnz** [comment]
Sorry, my mistake. I wasn't aware of the excludedPages setting. The plugin works outside the playground page. Thanks!

**Comment by LotarProject** [comment]
No problem :)

**Comment by paulhuysing** [comment]
Update to above issue - Operation of Edittable plugin is also broken so the issues must be related.
