### ISSUE TITLE
Datatables not working on Detritus release

### ISSUE THREAD

**Issue by chrisisbd** [LotarProject/dokuwiki-plugin-datatables#13]
I am trying the datatables plugin on Detritus and can't get it to work at all.

I have read through the other issue reporting that the latest release doesn't work on Ponder Stibbons but I can't really work out whether that is the same problem or not.

I have put the basic examples in both my playground area and in another page and all I see is the normal Dokuwiki tables.

**Comment by MarcoSchmitz** [comment]
I have the same problem. Any suggestions?

**Comment by Soeldner** [comment]
Any Logs? I tested it on 2 separate installations. tabledat works, see screenshot. But the design was not loaded at start... sometimes... see screenshot 2. perhaps the same "error"?

![dtatable](https://cloud.githubusercontent.com/assets/1868211/13252583/d1408b3c-da37-11e5-8dbe-926275183c55.jpg)

**Comment by MarcoSchmitz** [comment]
In the Apache error.log I found the following line:
File does not exist: /var/www/doku/lib/plugins/datatables/assets/datatables/extensions/Responsive/css/dataTables.responsive.min.css, referer: https://.....

Under the location /var/www/doku/lib/plugins/datatables/assets/datatables/extensions/Responsive/css/ I only found the following files:

responsive.bootstrap.min.css responsive.dataTables.min.css responsive.jqueryui.min.css

The file dataTables.responsive.min.css does not exist.

**Comment by chrisisbd** [comment]
On Tue, Feb 23, 2016 at 05:18:29AM -0800, MarcoSchmitz wrote:
>    In the Apache error.log I found the following line:
>    File does not exist:
>    /var/www/doku/lib/plugins/datatables/assets/datatables/extensions/Respo
>    nsive/css/dataTables.responsive.min.css, referer: https://.....
> 
>    Under the location
>    /var/www/doku/lib/plugins/datatables/assets/datatables/extensions/Respo
>    nsive/css/ I only found the following files:
> 
>    responsive.bootstrap.min.css responsive.dataTables.min.css
>    responsive.jqueryui.min.css
> 
>    The file dataTables.responsive.min.css does not exist.
> 
I found that DataTables doesn't work with all templates, it works with
the Dokuwiki default plugin and with Lotars but not always with others.

-- 
Chris Green

**Comment by LotarProject** [comment]
@chrisisbd the name of template ?

**Comment by chrisisbd** [comment]
On Tue, Feb 23, 2016 at 07:37:00AM -0800, Giuseppe Di Terlizzi wrote:
>    [1]@chrisisbd the name of template ?
> 
I was trying to use it with RoundBox and it doesn't work with that.

-- 
Chris Green

**Comment by Soeldner** [comment]
I can confirm the statement of chrisisbd. The css/js files in the head section loaded successfully.

#13 has nothing to do with these "bug".

![screenshot](https://cloud.githubusercontent.com/assets/1868211/13259440/a8133618-da57-11e5-9e0a-a130ca3b2019.jpg)
