### ISSUE TITLE
Datatables Not Working with Snippets Plugin

### ISSUE THREAD

**Issue by rgibsonohmh** [LotarProject/dokuwiki-plugin-datatables#18]
I have a Dokuwiki instance which has the datatables plugin and the snippets plugin.

With both plugins enabled, the popup which supports the snippets dialog is missing some button to preview and insert the various snippets into the edit document.

When I disable datatables, I am able to properly insert snippets via its popup.  I can verify this before and after clearing every cache I can find (local browser, DW CSS, DW JS, DW page cache).

I have already reached out to the snippets author and filed a bug report.  (https://github.com/turnermm/Updatable-Snippets-for-Dokuwiki/issues/19)

They are seeing the following error:

```
TypeError: JSINFO.plugin is undefined
if (JSINFO.plugin.datatables.enableForAllTables) {
```
I have also tried having the datatables plugin setting for all tables both on and off, and I get the same result.

**Comment by LotarProject** [comment]
Hi! Thanks for reporting this issue. Which version of DataTables plugin you have ?

Joseph

**Comment by rgibsonohmh** [comment]
Forgot to include that...

I have 2016-02-23 installed for DataTables and 2016-02-02 for snippets.  I have a fully-updated Detritus install.

**Comment by LotarProject** [comment]
Thanks! Can you type this in your browser in Developer Console ?

``typeof JSINFO.plugin``

and

``typeof JSINFO.plugin.datatables``

**Comment by rgibsonohmh** [comment]
typeof JSINFO.plugin returns the text 'object'

typeof JSINFO.plugin.datatables returns the same text.

**Comment by LotarProject** [comment]
Hi! I have changed the JS. Can you download the lastest version of plugin ?

**Comment by rgibsonohmh** [comment]
I was out of the office yesterday.

I have since upgraded the plugin to the latest version from the extension manager.

I am happy to report that with the Datatables plugin enable and the Snippets plugin enabled, I can properly insert the snippets.

This issue can now be closed.

Thanks,
Rob
