### ISSUE TITLE
Question:  Use default wiki table

### ISSUE THREAD

**Issue by MvErven** [LotarProject/dokuwiki-plugin-datatables#38]
In configuration:
What does this means?
plugin»datatables»enableForAllTables

I would like to have a very tine table (without all datatable items) 
Is this the configuration needed? 

In other words: Would this option only triggers datatable if de tags datatable are used?

Thanks in advance,
Michiel.

**Comment by LotarProject** [comment]
Hi, this options enable datatables for all tables in all DokuWiki pages without add ``<datatables>`` tag.

Joseph

**Comment by MvErven** [comment]
Great! I suspected so. 
Thanks for confirmation.

Michiel.
