### ISSUE TITLE
Strange Issue popped up

### ISSUE THREAD

**Issue by NoriSilverrage** [LotarProject/dokuwiki-plugin-datatables#5]
Was using DataTables a couple weeks back without any issue and just noticed today that it is no longer working.
Basically it appears that the functions for it aren't working.
Chrome says: Uncaught TypeError: $target_table.DataTable is not a function
js.php?t=bootstrap3&tseed=ed855a3e6f5f626b45c47eb0d32bce85

Running Release 2015-08-10 "Detritus" and DataTables Installed version:
2015-08-07

**Comment by LotarProject** [comment]
Hi! This error occur when the DataTable JS library is not loaded.

Follow this steps:
  * Clear all browser and DokuWiki JS cache (via ``<dokuwiki>/lib/exe/js.php?purge=true``).
  * Type ``jQuery.fn.DataTable.version`` in your JS console; the expected result is ``1.10.7``.

At your disposal,
Joseph

**Comment by NoriSilverrage** [comment]
Thanks for the response...
I figured out the issue and it was just me being dumb.
I was setting up documentation for Data Tables and put it under /wiki not realizing that anything under there is excluded. Removed the exclusion and it is working now.
