### ISSUE TITLE
Problems with Release 2023-04-04a "Jack Jackrum" 

### ISSUE THREAD

**Issue by Alexlutjen** [LotarProject/dokuwiki-plugin-datatables#73]
Since the update to Release 2023-04-04a "Jack Jackrum"

The Database plugin provides an error:
Error: Call to undefined function simplexml_load_string()
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the datatables plugin.

from log
2023-09-15 09:38:16
Error: Call to undefined function simplexml_load_string()
/var/www/html/dokuwiki-doc/lib/plugins/datatables/syntax.php(82)

**Comment by giterlizzi** [comment]
Hi,
the `simplexml_load_string` function require the XML library loaded in your PHP installation.

**Comment by Alexlutjen** [comment]
Hi,

Thank you for the quick response. I wil look into it.

Regards
